### ISSUE TITLE
PL/SQL Cop for SQLDev doesn't know PRAGMA UDF

### ISSUE THREAD

**Issue by dc55028** [Trivadis/cop-validators#3]
Hi,

with the version 2.2.0 of PL/SQL Cop, any "PRAGMA UDF;" in a package causes this error :
Blocker
E-0002: Syntax error. Please contact the author if the code compiles successfully in your environment.
no viable alternative at input 'UDF'

an example function definition is :
FUNCTION get_something(p_type VARCHAR2) return VARCHAR2 IS
    PRAGMA UDF;
    l_product_class VARCHAR2(10);
BEGIN
....

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting this issue. 

It's a bug of our parser. I've opened a corresponding [issue]( https://itracker.trivadis.com/issuetracker/browse/PLSQLCOP-258) in our private ticketing system. Should be fixed in the next release.

**Comment by PhilippSalvisberg** [comment]
Fixed. Will be part of next release.
